const cors = require("cors")
const dotenv = require("dotenv")
dotenv.config()
const express = require("express")
const app = express()
app.use(express.json())
app.use(cors())
require("./dbconnection.js")
const socket = require("./services/socketservices.js")

app.use("/uploads", express.static("uploads/"))
const gardenerController = require("./controllers/gardenerControllers.js")
app.use("/gardener", gardenerController)
const managerController = require("./controllers/managerControllers.js")
app.use("/manager", managerController)
const gardenController = require("./controllers/gardenControllers.js")
app.use("/garden", gardenController)
const adminController = require("./controllers/adminControllers.js")
app.use("/admin", adminController)
const taskController = require("./controllers/taskControllers.js")
app.use("/task", taskController)
const eventController=require("./controllers/eventControllers.js")
app.use("/event",eventController)

app.listen(8080, () => {
    console.log("Server is running on port 8080")
})